### PR TITLE
Refactored the module execution into __main__.py.

### PR DESCRIPTION
**Pull request by KleinerNull**

### CODE REVIEW

**Comment by KleinerNull** [comment]
Damn, this messed up the tests. Should look into that later...

**Comment by spurin** [comment]
Also accepted 1aa7b582bfef3f97ea413fad859a7bd6a08669d7 in 1.0.1

**Comment by spurin** [comment]
With regards to the other change in the pull request, I'm going to refactor the main class into it's own file and move away from the internal method calls so i'm skipping the last one (but borrowing the approach for the next release).  Thanks again for your efforts.

**Comment by spurin** [comment]
Closing, thanks for all efforts

**Pull request closed without merging**
